### PR TITLE
Update some route examples to cy.intercept

### PR DESCRIPTION
**Pull request by jennifer-shehane**
Updates a few recipes to use cy.intercept instead of deprecated cy.route

### CODE REVIEW

**Review by bahmutov — CHANGES_REQUESTED** [review]
the changed tests failed on CI?

**Comment by jennifer-shehane** [comment]
@bahmutov It worked on my machine! I'll have to relook at it I guess.

**Comment by bahmutov** [comment]
I believe you ;)

**Comment by jennifer-shehane** [comment]
Closing this as I don't have time to complete this work 😢

**Pull request closed without merging**
