### PR TITLE
example without stubbed local API to verify CORS

### PR DESCRIPTION
**Pull request by bahmutov**
Trying to investigate https://github.com/cypress-io/cypress/issues/9599 but seems even local API still uses the stubs correctly

Screen Shot 2020-12-09 at 3 24 43 PM

### CODE REVIEW

**Comment by bahmutov** [comment]
See the problem shown in https://github.com/cypress-io/cypress/issues/9602

Screen Shot 2020-12-09 at 4 04 49 PM

**Comment by rhogeranacleto** [comment]
### I have the exactly same problem.

It can be reproduced with the following simple code

```ts
it.only('maria', () => {
  cy.intercept('GET', '/me', { fixture: 'collaborator-user' }).as('me');

  cy.window().its('localStorage').invoke('setItem', 'token', 'APP_TOKEN');

  cy.visit('/');

  cy.wait('@me');
});
```
#### This is when the local server is running
image

#### This is when the local server is down
image

I'll keep using `route` and wait for a solution.

**Comment by bahmutov** [comment]
@rhogeranacleto can you open the DevTools Network tab and post a screenshot of the requests to confirm you get a failed `OPTIONS` call first?

**Comment by PatrickWalker** [comment]
I'm seeing the same locally and can get tests to pass by removing Authorization header in my application code from the request. Otherwise it fails

image


image


I was adding the header to the code and its the only change that causes it to be intercepted or not from what I can see

**Pull request merged**
