### PR TITLE
Cross domain file download

### LINKED ISSUE #565: File download triggers page load wait
Seems to trigger `onBeforeUnload` event callback. 

In a separate company project, as reported by the user, clicking on the `a` link downloads the file _and_ starts page load which times out.

Markup

Screen Shot 2020-09-14 at 11 56 34 AM

Note that the file is from another domain

Callstack

Screen Shot 2020-09-14 at 11 54 18 AM

### PR DESCRIPTION
**Pull request by bahmutov**
add example downloading local image and an image from another domain

- closes #565

Without `chromeWebSecurity: false` we get

Screen Shot 2020-09-14 at 5 53 15 PM

### CODE REVIEW

**Comment by bahmutov** [comment]
@Bkucera why would this trigger cross-domain error? I have seen for one user of ours "page loading..." that never resolves in this situation (see linked issue)

**Comment by Bkucera** [comment]
if the url is cross-origin, the download attribute will not have an affect. So the page is actually navigating. I would assume the image isn't downloaded

image
source: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a

**Comment by bahmutov** [comment]
Working in Chrome-based browsers is good in this case with `chromeWebSecurity: false`, the images are downloaded and checked

Screen Shot 2020-09-15 at 6 26 45 PM

**Comment by SidharthLala1** [comment]
@bahmutov So do we have a solution , i have already added "chromeWebSecurity": false in my cypress.json file.

What are the next steps to be followed to make this work. Please note that i am on cypress version # 4.12.1.

I hope that is not a problem.

**Comment by bahmutov** [comment]
For now I have opened another PR https://github.com/cypress-io/cypress-example-recipes/pull/569 with cross-origin JS and TXT file downloads. Would be nice to have a cross-domain CSV file download, since the browser seems to handle CSV files differently.

**Pull request merged**
