### PR TITLE
test spy retries, close #86

### LINKED ISSUE #86: Test spy retries
Seems spy via alias does not retry waiting for the function to be called.

### PR DESCRIPTION
**Pull request by bahmutov**
Failing test case for spy retries

### CODE REVIEW

**Comment by brian-mann** [comment]
Oomphf - I think these types of tests should go in the driver's integration tests. Unless there is some observable and explainable value to users it does not belong in recipes.

**Comment by bahmutov** [comment]
Maybe but I think users would benefit from three ways of spying example !

**Comment by brian-mann** [comment]
I agree - but this should just go into the docs. Since it's not actually testing a "real" scenario - we could just add these as a simple "Notes" or "Example" in the docs in the spying/stubbing guide.

**Comment by bahmutov** [comment]
Ok here and into docs.

**Comment by brian-mann** [comment]
Closing this - as these tests are in the driver - I believe they belong there. Recipes are about achieving real world use cases and not general purpose. If we could bake these into the recipes in a useful way I'd pull in.

**Pull request closed without merging**
