### PR TITLE
add Shadow DOM / LitElement recipe

### PR DESCRIPTION
**Pull request by 43081j**
Just adding some stuff for lit-element and shadow dom docs/examples.

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@43081j We have some instructions for running recipe tests on 'pre-release' versions of Cypress here: https://github.com/cypress-io/cypress-example-recipes/blob/master/Development.md#recipes-for-upcoming-test-runner-versions Because if we ran these new tests in our CI now - they would run against 4.7.0 and fail, `.shadow()` is not defined. 

I'm sure @bahmutov can help if you have any questions on this process.

**Comment by bahmutov** [comment]
I have changed the base branch to match the upcoming `4.7.1` version of the test runner. Once this PR is merged there, our CI will automatically test pre-release builds of the test runner against the branch 4.7.1

**Comment by 43081j** [comment]
yeah to be honest im still getting my head around the dev setup with this repo. i couldn't find a way to get it working against my in-progress branch.

and on windows i still have a bunch of problems running cypress from the repo, so couldn't even `npm link` it. the initial install falls over because of node-sass somehow.

**Comment by chrisbreiding** [comment]
Any reason not to put the lit-element stuff under `testing-dom__shadow-dom`?

**Comment by bahmutov** [comment]
Looks good and passing with 4.8.0, merging

**Pull request merged**
