### PR TITLE
Add cypress-file-upload reference

### PR DESCRIPTION
**Pull request by abramenal**
Add reference to plugin that makes file upload testing easy.
Supports upload via plain HTML input components, framework-specific file inputs, drag-n-drops, etc.
Usage recipe is located inside: https://github.com/abramenal/cypress-file-upload/tree/master/example

Cypress docs PR: https://github.com/cypress-io/cypress-documentation/pull/1560

### CODE REVIEW

**Comment by abramenal** [comment]
@jennifer-shehane can you please assist in merging the PR?

**Comment by jennifer-shehane** [comment]
@bahmutov What's up with this `ci/circleci: after-tests` job?

**Comment by bahmutov** [comment]
hmm, interesting why this is not being built on Circle, one sec

**Comment by bahmutov** [comment]
ok, I think now it is working - for some reason we had "build forked pull request: Off" for this project on CircleCI

**Comment by abramenal** [comment]
Okay now they are failing 😄

**Comment by bahmutov** [comment]
no worries @abramenal - they are failing because we are not passing environment variables to forked pull requests, and the project is trying to record to Cypress Dashboard. I am fixing this.

**Comment by bahmutov** [comment]
perfect, thank you @abramenal

**Pull request merged**
