### PR TITLE
Remove file-upload-react example

### PR DESCRIPTION
**Pull request by BlueWinds**
Because we're adding `.selectFile()` in Cypress 9.3.0, we want to remove this outdated example. If people still need an example of how to use the new command, then we can improve our documentation, rather than have it live here in another repository.

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@BlueWinds Can you sign the CLA for this repo?

**Comment by BlueWinds** [comment]
> @BlueWinds Can you sign the CLA for this repo?

Done.

**Review by jennifer-shehane — APPROVED** [review]
This seems fine to merge in now ahead of the release even.

**Review by emilyrohrbough — APPROVED** [review]

**Review by cowboy — APPROVED** [review]

**Comment by jennifer-shehane** [comment]
Going to wait to merge this in until the link in the docs to this example is removed in https://github.com/cypress-io/cypress-documentation/pull/4241

**Pull request merged**
