### PR TITLE
update and expand the custom command recipe

### PR DESCRIPTION
**Pull request by bahmutov**
for https://github.com/cypress-io/cypress/issues/8127
- cleaned up custom command recipe in JavaScript + `support/index.d.ts`
- copied and updated the custom command recipe to be only TypeScript `support/index.ts` + `support/index.d.ts`

before:
Screen Shot 2020-08-03 at 12 03 28 PM

after:
async-add

### CODE REVIEW

**Comment by bahmutov** [comment]
before:
Screen Shot 2020-08-03 at 12 11 38 PM

after:
Screen Shot 2020-08-03 at 12 12 10 PM

**Comment by bahmutov** [comment]
@jennifer-shehane is this matching the https://github.com/cypress-io/cypress/issues/8127#issuecomment-667905385 ? Seems to work for me, but it is nice to have a TS recipe for this

**Comment by jennifer-shehane** [comment]
This works with this definition `/// <reference path="../support/index.d.ts" />` although I feel like I removed and added this before and it changed nothing, must have been in between some settings. 

I don't understand why the instructions explicitly tell you to not use a `tsconfig.json` when this is the first thing we tell users to do in the TypeScript guide. This example seems to work with the `tsconfig.json` - removing the cypress reference paths.

**Comment by bahmutov** [comment]
Let me add it to the support file only, and once this lands, we can update the instructions. Also I will then add another recipe WITH tsconfig.json file

**Comment by bahmutov** [comment]
Actually what am I thinking - without tsconfig.json you DO need to reference the `index.d.ts` from every spec, otherwise it does not know about `cy` and any commands

reference

**Comment by jennifer-shehane** [comment]
This comment still says it's not working: https://github.com/cypress-io/cypress/issues/8127#issuecomment-668419763

**Comment by bahmutov** [comment]
The comment there says “file is outside the project” which I have no idea about

**Pull request merged**
